name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up credentials
        run: |
          echo "const ACCESS_VARIABLE = '${{ secrets.ACCESS_VARIABLE }}';" > /var/www/html/test-cicd/git_creds/variable.js
          
      - name: Copy website files to production server
        run: |
          scp -r index.html /var/www/html/

      - name: Restart NGINX on production server
        run: 'ssh systemctl restart nginx'


            


