name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: pradip-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up credentials
        run: |
          echo "${{ secrets.ACCESS_VARIABLE }}" > /var/www/html/test-cicd/Variable.js

      - name: Copy website files to production server
        run: |
          scp -r index.html :/var/www/html/

      - name: Restart NGINX on production server
        run: 'sudo systemctl restart nginx'

            


