name: Deploy Website

on:
  push:
    branches:
      - main  # Change this to match your repository's main branch

jobs:
  deploy:
    runs-on: 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : copy credential 
        run: | 
            

      - name: Deploy changes
        run: |
          sudo cp index.html /var/www/html/
          sudo systemctl restart nginx

