name: Deploy Website

on:
  push:
    branches:
      - main  # Change this to match your repository's main branch

jobs:
  deploy:
    runs-on: pradip-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up credentials
         run: |
          
          cat << EOF > /var/www/html/test-cicd/git_creds/Variable.js
          ${{ vars.ACCESS_VARIABLE }}
          EOF
          
      

      - name: Copy website files to production server
        run: |
          scp -r index.html /var/www/html/

         
          
      - name: Restart NGINX on production server
        run: 'sudo systemctl restart nginx'
            


